### ISSUE TITLE
Decompilation bug

### ISSUE THREAD

**Issue by epicabsol** [TheLegendOfMataNui/SAGESharp#4]
The temporary empty true block node created when decompiling needs to have its length set in the `nodeLengths` dictionary.

Add 
```
nodeLengths.Add(trueNode, 0);
```

at /SAGESharp/OSI/ControlFlow/SubroutineGraph.cs#L88

**Comment by Vraiment** [comment]
Gladly, I've created PR #5 with the changes.

I just want to note you don't need action from me, the automation is in place so you just push your changes to the repo, once they are merged to the master branch you create a new release and it will automatically get pushed to NuGet.org. **Is very important that the release version must match the version in *SAGESharp/Properties/AssemblyInfo.cs* and should not be repeated in NuGet**
